blank_issues_enabled: false
contact_links:
  - name: "\U0001F4AC Discussions"
    url: https://github.com/werf/werf/discussions/categories/general
    about: Ask a question
  - name: "\U0001F4AC Telegram channel [EN]"
    url: https://t.me/werf_io
    about: Ask a question
  - name: "\U0001F4AC Telegram channel [RU]"
    url: https://t.me/werf_ru
    about: Ask a question
